apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-secrets-webhook-limited
  labels:
    app.kubernetes.io/name: vault-secrets-webhook
    app.kubernetes.io/part-of: vault
    app.kubernetes.io/component: secrets-webhook
    app.kubernetes.io/version: 1.15.2
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: vault-secrets-webhook
subjects:
  - kind: ServiceAccount
    name: vault-secrets-webhook
    namespace: infrastructure
