apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-secrets-webhook
  labels:
    app.kubernetes.io/name: vault-secrets-webhook
    app.kubernetes.io/part-of: vault
    app.kubernetes.io/component: secrets-webhook
    app.kubernetes.io/version: 1.15.2
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - update
