apiVersion: v1
kind: Service
metadata:
  name: vault-secrets-webhook
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: vault-secrets-webhook
    app.kubernetes.io/part-of: vault
    app.kubernetes.io/component: secrets-webhook
    app.kubernetes.io/version: 1.15.2
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vault-secrets-webhook
    app.kubernetes.io/part-of: vault
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
