apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-cainjector
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: injector
    app.kubernetes.io/version: 1.8.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-cainjector
subjects:
  - name: cert-manager-cainjector
    kind: ServiceAccount
    namespace: infrastructure
