apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-cainjector
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: injector
    app.kubernetes.io/version: 1.8.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cainjector
      app.kubernetes.io/part-of: cert-manager
  replicas: 1
  template:
    metadata:
      annotations:
        diun.enable: "true"
        diun.regopt: docker.io
        diun.watch_repo: "true"
        diun.include_tags: "^\\d+\\.\\d+\\.\\d+-debian-\\d+-r\\d+$"
      labels:
        app.kubernetes.io/name: cainjector
        app.kubernetes.io/part-of: cert-manager
        app.kubernetes.io/component: injector
        app.kubernetes.io/version: 1.8.0
    spec:
      serviceAccountName: cert-manager-cainjector
      containers:
        - name: cainjector
          image: bitnami/cainjector:1.8.0
          args:
            - --v=2
            - --leader-election-namespace=kube-system
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          resources:
            requests:
              cpu: 8m
              memory: 128Mi
            limits:
              cpu: 32m
              memory: 192Mi
