apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - statefulset.yaml
  - service.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 14.3.0
configMapGenerator:
  - name: postgresql-env
    namespace: infrastructure
    env: configuration/postgresql.env
  - name: postgresql-scripts
    namespace: infrastructure
    files:
      - scripts/pre-stop.sh