apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 14.3.0
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: postgresql
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 14.3.0
  annotations:
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: postgresql
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: postgresql
      
