kind: ServiceAccount
apiVersion: v1
metadata:
  name: postgresql
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/version: 14.3.0