apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultwarden
  namespace: leuchtturm-io
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/part-of: vaultwarden
    app.kubernetes.io/component: server
    app.kubernetes.io/version: 1.24.0
