apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea
  namespace: medium-place
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: gitea
    app.kubernetes.io/component: server
    app.kubernetes.io/version: 1.16.8
