apiVersion: v1
kind: Service
metadata:
  name: vault-operator
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/part-of: vault
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: 1.15.2
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/part-of: vault
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: http-metrics
      protocol: TCP
      port: 8383
      targetPort: http-metrics
