kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: vault
    app.kubernetes.io/component: vault
    app.kubernetes.io/version: 1.10.3
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - update
      - patch
