apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: cert-manager-webhook
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: webhook
    app.kubernetes.io/version: 1.8.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager-webhook
      app.kubernetes.io/part-of: cert-manager
  replicas: 1
  template:
    metadata:
      annotations:
        diun.enable: "true"
        diun.regopt: docker.io
        diun.watch_repo: "true"
        diun.include_tags: "^\\d+\\.\\d+\\.\\d+-debian-\\d+-r\\d+$"
      labels:
        app.kubernetes.io/name: cert-manager-webhook
        app.kubernetes.io/part-of: cert-manager
        app.kubernetes.io/component: webhook
        app.kubernetes.io/version: 1.8.0
    spec:
      serviceAccountName: cert-manager-webhook
      containers:
        - name: webhook
          image: bitnami/cert-manager-webhook:1.8.0
          args:
            - --v=2
            - --secure-port=10250
            - --dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)
            - --dynamic-serving-ca-secret-name=cert-manager-webhook-ca
            - --dynamic-serving-dns-names=cert-manager-webhook.infrastructure.svc.cluster.local
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: https
              protocol: TCP
              containerPort: 10250
          resources:
            requests:
              cpu: 4m
              memory: 32Mi
            limits:
              cpu: 8m
              memory: 64Mi
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /livez
              port: 6080
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 6080
