apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-dynamic-serving
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: cert-manager-webhook
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: webhook
    app.kubernetes.io/version: 1.8.0
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - cert-manager-webhook-ca
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
