apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: cert-manager-webhook
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: webhook
    app.kubernetes.io/version: 1.8.0
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cert-manager-webhook
    app.kubernetes.io/part-of: cert-manager
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
