apiVersion: v1
kind: ServiceAccount
metadata:
  name: synapse
  namespace: medium-place
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/part-of: synapse
    app.kubernetes.io/component: server
    app.kubernetes.io/version: 1.59.1
