apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: gitea
    app.kubernetes.io/component: server
    app.kubernetes.io/version: 1.16.8
configMapGenerator:
  - name: gitea-env
    namespace: medium-place
    env: configuration/gitea.env
