apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: external-dns-env
    namespace: infrastructure
    env: configuration/external-dns.env
