apiVersion: v1
kind: Service
metadata:
  name: external-dns
  namespace: "infrastructure"
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/part-of: external-dns
    app.kubernetes.io/component: external-dns
    app.kubernetes.io/version: 0.11.1
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/component: external-dns
  ports:
    - name: http
      protocol: TCP
      port: 7979
      targetPort: http
