apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/part-of: external-dns
    app.kubernetes.io/component: external-dns
    app.kubernetes.io/version: 0.11.1
