apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: teslamate
    app.kubernetes.io/component: server
    app.kubernetes.io/version: 1.26.1
configMapGenerator:
  - name: teslamate-grafana-env
    namespace: medium-place
    env: configuration/teslamate-grafana.env