kind: ServiceAccount
apiVersion: v1
metadata:
  name: teslamate-grafana
  namespace: medium-place
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: teslamate
    app.kubernetes.io/component: server
    app.kubernetes.io/version: 1.26.1