apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingressclass.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: nginx-ingress-controller
    app.kubernetes.io/part-of: nginx-ingress-controller
    app.kubernetes.io/component: controller
    version: 1.2.0
