apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-controller-controller
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: nginx-ingress-controller
    app.kubernetes.io/part-of: nginx-ingress-controller
    app.kubernetes.io/component: controller
    version: 1.2.0
