apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-controller-nginx
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: nginx-ingress-controller
    app.kubernetes.io/part-of: nginx-ingress-controller
    app.kubernetes.io/component: server
    version: 1.21.6
