apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-nginx
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: nginx-ingress-controller
    app.kubernetes.io/part-of: nginx-ingress-controller
    app.kubernetes.io/component: server
    version: 1.21.6
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx-ingress-controller
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
