apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: pgpool
    app.kubernetes.io/part-of: postgresql
    app.kubernetes.io/component: pooler
    app.kubernetes.io/version: 4.3.1
configMapGenerator:
  - name: postgresql-pgpool-env
    namespace: infrastructure
    env: configuration/pgpool.env
