apiVersion: v1
kind: Service
metadata:
  name: cert-manager-metrics
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.8.0
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller
  ports:
    - name: http
      protocol: TCP
      port: 9402
      targetPort: http
