apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.8.0
