apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgresql-backup
  namespace: infrastructure
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure.svc.cluster.local:8200
            vault.security.banzaicloud.io/vault-role: postgresql
        spec:
          serviceAccountName: postgresql
          containers:
            - name: postgresql-backup
              image: postgres:14.2
              command: ["/bin/sh"]
              args:
                [
                  "-c",
                  'pg_dumpall -U postgres -h $PGHOST > /data/backup-$(date +"%m-%d-%Y-%H-%M").sql',
                ]
              env:
                - name: PGHOST
                  value: postgresql-postgresql-ha-pgpool.infrastructure.svc
                - name: PGPASSWORD
                  value: vault:secret/data/infrastructure/postgresql/authentication#postgres_password
              volumeMounts:
                - mountPath: /data
                  name: data-postgresql-backup
          restartPolicy: Never
          volumes:
            - name: data-postgresql-backup
              persistentVolumeClaim:
                claimName: data-postgresql-backup
