apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diun
  labels:
    app.kubernetes.io/name: diun
    app.kubernetes.io/part-of: diun
    app.kubernetes.io/component: server
    app.kubernetes.io/version: 4.21.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diun
subjects:
  - kind: ServiceAccount
    name: diun
    namespace: infrastructure