apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - statefulset.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: diun
    app.kubernetes.io/part-of: diun
    app.kubernetes.io/component: server
    app.kubernetes.io/version: 4.21.0
configMapGenerator:
  - name: diun-env
    namespace: infrastructure
    env: configuration/diun.env
  - name: diun-config
    namespace: infrastructure
    files:
      - configuration/images.yaml