apiVersion: v1
kind: ServiceAccount
metadata:
  name: diun
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: diun
    app.kubernetes.io/part-of: diun
    app.kubernetes.io/component: server
    app.kubernetes.io/version: 4.21.0