apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mastodon-redis
  namespace: medium-place
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/component: kv-store
    app.kubernetes.io/version: 6.2.7
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: mastodon
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure.svc.cluster.local:8200
        vault.security.banzaicloud.io/vault-role: mastodon
        diun.enable: "true"
        diun.regopt: docker.io
        diun.watch_repo: "true"
        diun.include_tags: "^\\d+\\.\\d+\\.\\d+-debian-\\d+-r\\d+$"
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: mastodon
        app.kubernetes.io/component: kv-store
        app.kubernetes.io/version: 6.2.7
    spec:
      serviceAccountName: mastodon-redis
      securityContext:
        fsGroup: 1001
      containers:
        - name: redis
          image: bitnami/redis:6.2.7-debian-10-r20
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          envFrom:
           - configMapRef:
               name: mastodon-redis-env
          ports:
            - name: redis
              protocol: TCP
              containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /bitnami/redis/data
          resources:
            requests:
              cpu: 16m
              memory: 16Mi
            limits:
              cpu: 32m
              memory: 32Mi
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: medium-place
        labels:
          app.kubernetes.io/name: redis
          app.kubernetes.io/part-of: mastodon
          app.kubernetes.io/component: kv-store
      spec:
        storageClassName: scw-bssd-retain
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
